# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

include:
  - project: sysadmin/ci-utilities
    file:
     - /gitlab-templates/linux-qt6.yml

# Commented out because they don't support appstreamqt yet, and it's probably fine
#     - /gitlab-templates/freebsd-qt6.yml

# Specifically for testing the apk backend
# Synced from: https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/community/discover/APKBUILD
alpine-ci:
  image: alpine:edge
  stage: build
  script:
    - apk update
    - >
      apk add alpine-sdk \
              appstream-dev \
              attica-dev \
              extra-cmake-modules \
              karchive-dev \
              kauth-dev \
              kcmutils-dev \
              kconfig-dev \
              kcoreaddons-dev \
              kcrash-dev \
              kdbusaddons-dev \
              kdeclarative-dev \
              ki18n-dev \
              kidletime-dev \
              kio-dev \
              kirigami-addons-dev \
              kirigami-dev \
              kitemmodels-dev \
              knewstuff-dev \
              kstatusnotifieritem-dev \
              kuserfeedback-dev \
              kxmlgui-dev \
              libapk-qt-dev \
              purpose-dev \
              qcoro-dev \
              qt6-qtbase-dev \
              qt6-qtdeclarative-dev \
              samurai
    - >
      cmake -B build \
        -DCMAKE_BUILD_TYPE=RelWithDebInfo \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=lib \
        -DCMAKE_DISABLE_FIND_PACKAGE_Snapd=ON \
        -DWITH_KCM=OFF
    - cmake --build build -- -j 8
