# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

include:
 - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/linux-qt6.yml

# Commented out because they don't support appstreamqt yet, and it's probably fine
# - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/freebsd-qt6.yml
